trigger:
- master
name: $(Date:yyyyMMdd)$(Rev:.r)

stages:
- stage: Build
  jobs:

  - job: 'Build'
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        Phase: 'STARTED'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world'
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        Phase: 'COMPLETED'
  - job: 'Test'
    dependsOn: 'Build'
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        upstream: 'Build'
        Phase: 'STARTED'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.6'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip
        pip install -r django-basic/requirements.txt
      displayName: 'Install dependencies'

    - script: |
        pip install pytest-django
        cd django-basic/azuredemo
        pytest --junitxml=../../reports/django-basic.xml
      displayName: 'Run tests'

    - task: PublishTestResults@2
      inputs:
        testResultsFiles: 'reports/django-basic.xml'
        testRunTitle: 'Test'
      condition: succeededOrFailed()
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        upstream: 'Build'
        Phase: 'COMPLETED'
- stage: Test
  jobs:

  - job: "Deploy"
    steps:
    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        upstream: 'Test'
        Phase: 'STARTED'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          # Write your commands here
          
          echo 'Hello world '

    - task: ServiceNow-DevOps-Agent-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        upstream: 'Test'
        Phase: 'COMPLETED'

  - job: "Prod"
    pool: server
    dependsOn: "Deploy"
    steps:
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        UpstreamJob: 'Deploy'
        Phase: 'STARTED'
    - task: Delay@1
      inputs:
        delayForMinutes: '0'
    - task: ServiceNow-DevOps-Server-Change-Acceleration@1
      inputs:
        connectedServiceName: 'amar_devops'
        UpstreamJob: 'Deploy'
      
    - task: ServiceNow-DevOps-Server-Job-Notification@1
      inputs:
        connectedServiceName: 'amar_devops'
        UpstreamJob: 'Deploy'
        Phase: 'COMPLETED'
      condition: true
